name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up SSH access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no FoodConnect@4.201.144.173 << 'EOF'
            cd /home/FoodConnect/foodconnect-backend/products-manager
            git pull origin main
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
          EOF
