name: Deploy Product Manager

on:
  push:
    branches:
      - main  # ou sua branch de deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Adiciona chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Envia projeto products-manager para a VM
        run: |
          # Conecta à VM, limpa o diretório de destino e cria o novo diretório
          ssh -o StrictHostKeyChecking=no FoodConnect@4.201.144.173 "
            rm -rf ~/foodconnect-backend/products-manager &&
            mkdir -p ~/foodconnect-backend/products-manager"
          
          # Envia o conteúdo da pasta de backend do repositório para a VM
          scp -r ./foodconnect-backend/* FoodConnect@4.201.144.173:~/foodconnect-backend/products-manager

      - name: Builda e sobe o container na VM
        run: |
          # Conecta à VM, entra no diretório do projeto e executa os comandos do Docker
          ssh -o StrictHostKeyChecking=no FoodConnect@4.201.144.173 "
            cd ~/foodconnect-backend/products-manager &&
            docker compose build &&
            docker compose up -d"
